name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core
  - jupyterlite-xeus
  - xeus-sqlite
  - pip:
    - catppuccin-jupyterlab
    - jupyterlab-night
    - jupyterlab_miami_nights
    - JLDracula
    - jupyterlab-language-pack-pt-BR
  
