name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.6
  - jupyterlite-xeus >=4
  - xeus-sqlite
  - cmake 
  - nlohmann_json 
  - xtl 
  - cppzmq 
  - xeus 
  - sqlite 
  - sqlitecpp 
  - cpp-tabulate ==1.5 
  - xvega 
  - xproperty 
  - xtl 
  - cppzmq 
  - xproperty 
  - jupyterlab
