name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-sqlite
  - xeus
  - catppuccin-jupyterlab
  - pip:
    - jupyterlab-night
    - jupyterlab_miami_nights
    - JLDracula
